import {server} from "../constant/serverPath"

export const apiPath = server + "/api"
export const healthDataPath = apiPath + "/health"
export const allHealthDataPath = healthDataPath + "/all"
export const healthPlanPath = healthDataPath + "/plan"
export const heartRatePath = healthDataPath + "/heartRate"
export const bloodOxygenPath = healthDataPath + "/bloodOxygen"
export const activityPath = healthDataPath + "/activity"
export const drugPath = healthDataPath + "/drug"