### Fetch Weather
GET http://localhost:3000/api/weather/?lat=51.5007&lon=0.1246&cityName=Abbey+Wood


### Delete weather cache
# DELETE http://localhost:3000/api/weather/?id=7302135
DELETE http://localhost:3000/api/weather/?id=3333229

### 
GET http://localhost:3000/api/aqi/?lat=51.5007&lon=0.1246

###
POST http://localhost:3000/api/health/
content-type: application/json

{
    "userId": "123456", 
    "heartRate": [
        {"quantity": 123, "id": "123123", "startTime": "2021-08-04T00:38:23.305Z", "endTime": "2021-08-04T00:38:23.305Z"},
        {"quantity": 456, "id": "123124", "startTime": "2021-08-04T00:39:23.305Z", "endTime": "2021-08-04T00:39:23.305Z"}
    ], 
    "bloodOxygen": [
        {"quantity": 99, "id": "456455", "startTime": "2021-08-04T00:38:23.305Z", "endTime": "2021-08-04T00:38:23.305Z"}
    ], 
    "drugUsage": [
        {"name": "Aspirin", "quantity": 1, "id": "123", "time": "2021-08-04T00:38:23.305Z"}
    ],
    "activity": [
        {"name": "walk", "quantity": 1000, "id": "456455", "time": "2021-08-04T00:38:23.305Z"}
    ]
}

### 
GET http://localhost:3000/api/health/?userId=123456

### 
DELETE http://localhost:3000/api/health/?userId=123456

### 
GET http://localhost:3000/api/health/all

### 
GET http://localhost:3000/api/health/heartRate

### 
GET http://localhost:3000/api/health/bloodOxygen

### 
GET http://localhost:3000/api/health/activity

### 
GET http://localhost:3000/api/health/drug

### 
POST http://localhost:3000/api/health/plan/
content-type: application/json

{
    "userId": "123456",
    "activity": {
        "name": "walk",
        "quantity": 1000,
        "timeInterval": "1-day"
    }
}

### 
POST http://localhost:3000/api/health/plan/all
content-type: application/json

{
    "activity": {
        "name": "run",
        "quantity": 1000,
        "timeInterval": "2-day"
    },
    "drug": {
        "name": "Aspirin",
        "quantity": 1,
        "timeInterval": "2-day"
    }
}

### 
GET http://localhost:3000/api/health/plan/?userId=123456
